apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-app
  template:
    metadata:
      labels:
        app: clinic-app
    spec:
      containers:
        - name: clinic-container
          image: clinic_img:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: clinic-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clinic-secret
                  key: DB_PASSWORD