apiVersion: v1
kind: ConfigMap
metadata:
  name: clinic-config
data:
  MYSQL_DATABASE: "clinic_db"
  MYSQL_USER: "clinic_user"
  DB_HOST: "mysql-clinic"
  DB_PORT: "3307"
  DB_USERNAME: "clinic_user"
  DB_DATABASE: "clinic_db"
  NODE_ENV: "production"