apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-clinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-clinic
  template:
    metadata:
      labels:
        app: mysql-clinic
    spec:
      containers:
        - name: mysql
          image: mysql:8.4.7
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: clinic-secret
            - configMapRef:
                name: clinic-config
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-clinic-pvc