apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-clinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-clinic
  template:
    metadata:
      labels:
        app: mysql-clinic
    spec:
      containers:
        - name: mysql
          image: mysql:8.0  
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12346578"
            - name: MYSQL_PASSWORD
              value: "abcd1234"
            - name: MYSQL_DATABASE
              value: "clinic_db"
            - name: MYSQL_USER
              value: "clinic_user"
          # MySQL 8.0 supports this parameter
          command:
            - "mysqld"
            - "--default-authentication-plugin=mysql_native_password"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-clinic-pvc