apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:30080,http://spring-service:8080"
  CLINICAL_SERVICE_URL: "http://nestjs-service:3000/api"
  DB_ENGINE: "django.db.backends.mysql"
  DB_NAME: "genomic_db"
  DB_USER: "genomic_user"
  DB_HOST: "django-mysql"
  DB_PORT: "3306"