apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmUtY2hhbmdlLWluLXByb2R1Y3Rpb24=  # your-secret-key-here-change-in-production
  DB_PASSWORD: Z2Vub21pYzEyMzQ=  # genomic1234