apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-mysql
  template:
    metadata:
      labels:
        app: django-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4.7
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: django-mysql-secret
            - configMapRef:
                name: django-mysql-config
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: django-mysql-pvc