apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: genosentinel
data:
  db-host: "mysql-service"
  db-port: "3306"
  db-name: "genosentinel"
  db-user: "genosentinel_user"
  spring-datasource-url: "jdbc:mysql://mysql-service:3306/genosentinel"
  spring-datasource-username: "genosentinel_user"
  server-port: "3003"
  server-servlet-context-path: "/genosentinel"
  jwt-expiration: "86400000"
  log-level: "DEBUG"
  spring-jpa-hibernate-ddl-auto: "validate"
  spring-jpa-show-sql: "true"
  # Add these properties to fix the issue
  spring-jpa-properties-hibernate-query-validation-mode: "none"
  spring-data-jpa-repositories-bootstrap-mode: "deferred"