apiVersion: v1 
kind: ConfigMap
metadata:
  name: auth-config
data:
  MYSQL_DATABASE: "genosentinel"
  MYSQL_USER: "genosentinel_user"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/genosentinel"
  SPRING_DATASOURCE_USERNAME: "genosentinel_user"
  